# Generated by Django 5.1.4 on 2026-08-28 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=255)),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('filas_leidas', models.PositiveIntegerField(default=0)),
                ('creados', models.PositiveIntegerField(default=0)),
                ('actualizados', models.PositiveIntegerField(default=0)),
                ('sin_cambios', models.PositiveIntegerField(default=0)),
                ('omitidos', models.PositiveIntegerField(default=0)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Import batches',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Número de requerimiento')),
                ('categoria', models.CharField(choices=[('proyecto', 'Proyecto'), ('requerimiento', 'Requerimiento'), ('incidencia', 'Incidencia')], db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
                ('fecha_solicitada', models.DateField(blank=True, null=True, verbose_name='Fecha solicitada')),
                ('funcional_solicitante', models.CharField(blank=True, default='', max_length=255, verbose_name='Funcional solicitante')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('avance', models.PositiveSmallIntegerField(default=0, verbose_name='Porcentaje de avance')),
                ('asignado', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Asignado a')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('estatus', models.CharField(db_index=True, default='Desarrollo', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['categoria', 'codigo'],
                'indexes': [models.Index(fields=['categoria', 'estatus'], name='tracker_tic_categor_d9cb2f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('avance__gte', 0), ('avance__lte', 100)), name='avance_entre_0_y_100')],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True, default='')),
                ('valor_nuevo', models.TextField(blank=True, default='')),
                ('origen', models.CharField(choices=[('creacion', 'Creación'), ('edicion', 'Edición'), ('importacion', 'Importación')], default='edicion', max_length=20)),
                ('archivo', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tracker.ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ticket histories',
                'ordering': ['-creado_en'],
            },
        ),
    ]
