# Generated by Django 5.1.4 on 2026-08-28 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tracker.ticket'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('responsable', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Responsable')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('lista', 'Lista'), ('bloqueada', 'Bloqueada')], db_index=True, default='pendiente', max_length=20)),
                ('avance', models.PositiveSmallIntegerField(default=0, verbose_name='Avance')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], db_index=True, default='media', max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_index=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tracker.ticket')),
            ],
            options={
                'ordering': ['ticket', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tracker.tarea'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['estado', 'responsable'], name='tracker_tar_estado_d8f754_idx'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(('avance__gte', 0), ('avance__lte', 100)), name='tarea_avance_entre_0_y_100'),
        ),
    ]
