# Generated by Django 5.1.4 on 2026-09-09 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_tickethistory_ticket_tarea_tickethistory_tarea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_fin',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha final'),
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('fecha_hora', models.DateTimeField(db_index=True, verbose_name='Fecha y hora')),
                ('duracion_minutos', models.PositiveSmallIntegerField(default=60, verbose_name='Duración (minutos)')),
                ('lugar', models.CharField(blank=True, default='', help_text='Sala física, o vacío si es virtual', max_length=255, verbose_name='Lugar')),
                ('enlace', models.URLField(blank=True, default='', help_text='Teams, Meet, Zoom…', verbose_name='Enlace')),
                ('participantes', models.TextField(blank=True, default='', help_text='Un nombre o correo por línea', verbose_name='Participantes')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Agenda o notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='tracker.tarea')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='tracker.ticket')),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('nota', models.TextField(blank=True, default='', verbose_name='Nota')),
                ('fecha', models.DateField(db_index=True, verbose_name='Avisar el día')),
                ('visto', models.BooleanField(db_index=True, default=False, verbose_name='Atendido')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='tracker.tarea')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='tracker.ticket')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['fecha', '-creado_en'],
                'indexes': [models.Index(fields=['visto', 'fecha'], name='tracker_rec_visto_90afed_idx')],
            },
        ),
    ]
